### ISSUE TITLE
SimpleCov docs

### ISSUE THREAD

**Issue by connorshea** [KnapsackPro/docs.knapsackpro.com#174]
It'd probably be a good idea to link to the SimpleCov documentation talking about merging simplecov reports across execution environments: https://github.com/simplecov-ruby/simplecov?tab=readme-ov-file#merging-test-runs-under-different-execution-environments

Right now the simplecov page in the Knapsack docs only links to some blog posts specific to Semaphore CI, so I had to do a bit more digging to figure that out.

**Comment by ArturT** [comment]
Good point @connorshea.
I recall someone shared [a similar example for merging simplecov reports](https://github.com/simplecov-ruby/simplecov/issues/986#issuecomment-1164999210).

Would you like to help and propose a pull request to [this page](https://docs.knapsackpro.com/ruby/simplecov/)? I'd appreciate it.
It's [this file](https://github.com/KnapsackPro/docs.knapsackpro.com/blob/main/docusaurus/docs/ruby/simplecov.md).

**Comment by ArturT** [comment]
I've updated the docs:
https://docs.knapsackpro.com/ruby/simplecov/#how-to-merge-simplecov-reports-from-parallel-ci-nodes
